version: '3.9'

services:
    app:
        image: native:app
        container_name: React-native
        ports:
            - "19000:19000"
            - "19001:19001"
            - "19002:19002"
            - "19006:19006"
            - "8081:8081"
        env_file:
            - ./Docker/React/.env
        stdin_open: true
        tty: true
        volumes:
            - ./src:/var/app
        networks:
            - app

networks:
    app:
        driver: bridge